#!/bin/sh
IPT=$(which iptables)
IP6T=$(which ip6tables)
ADMIN="127.0.0.1"

echo "Enabling Firewall"

$IPT -F
$IPT -X
$IP6T -F
$IP6T -X

# IPv4 rules

$IPT -P INPUT DROP
$IPT -P OUTPUT DROP
$IPT -P FORWARD DROP

$IPT -I INPUT -j ACCEPT -p icmp --icmp-type echo-request

$IPT -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
$IPT -A OUTPUT -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT

$IPT -A INPUT -i lo -j ACCEPT
$IPT -A OUTPUT -o lo -j ACCEPT

for ip in $ADMIN;
  do
  $IPT -A INPUT -p tcp --dport 22 -s $ip -j ACCEPT
done

$IPT -A INPUT -j DROP

# IPv6 rules

$IP6T -P INPUT DROP
$IP6T -P OUTPUT DROP
$IP6T -P FORWARD DROP

$IP6T -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
$IP6T -A OUTPUT -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT

$IP6T -A INPUT -i lo -j ACCEPT
$IP6T -A OUTPUT -o lo -j ACCEPT

$IP6T -A INPUT -j DROP

